name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.16.6"

    - name: Habilitar Flutter Web
      run: flutter config --enable-web

    - name: Instalar dependências
      run: flutter pub get

    - name: Build do Flutter Web
      run: flutter build web --release --web-renderer html

    - name: Publicar no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
