name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.2"

    - name: Habilitar Flutter Web
      run: flutter config --enable-web

    - name: Instalar dependências
      run: flutter pub get

    - name: Criar variaveis de ambiente
      run: |
        touch .env
        echo polaroid_image=${{ secrets.polaroid_image }} >> .env
        echo best_moments_1=${{ secrets.best_moments_1 }} >> .env
        echo best_moments_2=${{ secrets.best_moments_2 }} >> .env
        echo best_moments_3=${{ secrets.best_moments_3 }} >> .env
        echo firebase_api_key=${{ secrets.firebase_api_key }} >> .env
        cat .env

    - name: Build do Flutter Web
      run: flutter build web --release

    - name: Publicar no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
